function cripto(texto) {
  const lista = {
    q: "a1",
    w: "2a",
    e: "I ",
    r: "Cb",
    t: "b2",
    y: "b3",
    u: " C",
    i: "2 ",
    o: "0 ",
    p: "d1",
    a: " 3",
    s: "d3",
    d: "e1",
    f: "e2",
    g: "e3",
    h: "f1",
    j: "f2",
    k: "l2",
    l: "f3",
    ç: "g1",
    z: "g2",
    x: "g3",
    c: "A1",
    v: "2A",
    b: "A3",
    n: "B1",
    m: "Bl",
    Q: "B3",
    W: "C1",
    E: "2C",
    R: "C3",
    T: "D1",
    Y: "D2",
    U: "D3",
    I: "Oi",
    O: "Kp",
    P: "E3",
    A: "Ga",
    S: "F2",
    D: "F3",
    F: "a4",
    G: "a5",
    H: "a6",
    J: "b4",
    K: "b5",
    L: "b6",
    Ç: "c4",
    Z: "c5",
    X: "c6",
    C: "d4",
    V: "d5",
    B: "d6",
    N: "e4",
    M: "e5",
    Á: "e6",
    À: "A4",
    Â: "A5",
    Ã: "A6",
    á: "B4",
    à: "Bm",
    ã: "B6",
    â: "C4",
    É: "C5",
    È: "C6",
    Ê: "Eg",
    è: "E5",
    é: "E6",
    ê: "F4",
    Í: "Fb",
    Ì: "F6",
    Î: "a7",
    ì: "a8",
    í: "a9",
    î: "b7",
    Ó: "b8",
    Ò: "b9",
    Õ: "c7",
    Ô: "c8",
    ò: "c9",
    ó: "d7",
    ô: "d8",
    õ: "d9",
    Ú: "e7",
    Ù: "e8",
    Û: "e9",
    ú: "f7",
    ù: "f8",
    û: "f9",
    " ": "s3",
    ".": "p2",
    ",": "P6",
    "?": "k9",
    "!": "J5",
    1: "I5",
    2: "Tt",
    3: "I2",
    4: "5I",
    5: "r6",
    6: "i6",
    7: "5R",
    8: "i9",
    9: "L3",
    0: "k2",
  };
  var palavra = texto;
  var novaPalavra = "";

  for (var n = 0; n < palavra.length; n++) {
    for (var n1 = 0; n1 < Object.values(lista).length; n1++) {
      if (palavra[n] === Object.keys(lista)[n1]) {
        novaPalavra = novaPalavra + Object.values(lista)[n1];
      }
    }
  }
  return novaPalavra;
}

function descripto(texto) {
  const lista = {
    q: "a1",
    w: "2a",
    e: "I ",
    r: "Cb",
    t: "b2",
    y: "b3",
    u: " C",
    i: "2 ",
    o: "0 ",
    p: "d1",
    a: " 3",
    s: "d3",
    d: "e1",
    f: "e2",
    g: "e3",
    h: "f1",
    j: "f2",
    k: "l2",
    l: "f3",
    ç: "g1",
    z: "g2",
    x: "g3",
    c: "A1",
    v: "2A",
    b: "A3",
    n: "B1",
    m: "Bl",
    Q: "B3",
    W: "C1",
    E: "2C",
    R: "C3",
    T: "D1",
    Y: "D2",
    U: "D3",
    I: "Oi",
    O: "Kp",
    P: "E3",
    A: "Ga",
    S: "F2",
    D: "F3",
    F: "a4",
    G: "a5",
    H: "a6",
    J: "b4",
    K: "b5",
    L: "b6",
    Ç: "c4",
    Z: "c5",
    X: "c6",
    C: "d4",
    V: "d5",
    B: "d6",
    N: "e4",
    M: "e5",
    Á: "e6",
    À: "A4",
    Â: "A5",
    Ã: "A6",
    á: "B4",
    à: "Bm",
    ã: "B6",
    â: "C4",
    É: "C5",
    È: "C6",
    Ê: "Eg",
    è: "E5",
    é: "E6",
    ê: "F4",
    Í: "Fb",
    Ì: "F6",
    Î: "a7",
    ì: "a8",
    í: "a9",
    î: "b7",
    Ó: "b8",
    Ò: "b9",
    Õ: "c7",
    Ô: "c8",
    ò: "c9",
    ó: "d7",
    ô: "d8",
    õ: "d9",
    Ú: "e7",
    Ù: "e8",
    Û: "e9",
    ú: "f7",
    ù: "f8",
    û: "f9",
    " ": "s3",
    ".": "p2",
    ",": "P6",
    "?": "k9",
    "!": "J5",
    1: "I5",
    2: "Tt",
    3: "I2",
    4: "5I",
    5: "r6",
    6: "i6",
    7: "5R",
    8: "i9",
    9: "L3",
    0: "k2",
  };
  var palavra = texto;
  var novaPalavra = "";
  var cod = "";
  for (var n = 0; n < palavra.length; n++) {
    cod = cod + palavra[n];

    if (cod.length / 2 === 1) {
      for (var n1 = 0; n1 < Object.values(lista).length; n1++) {
        if (cod === Object.values(lista)[n1]) {
          novaPalavra = novaPalavra + Object.keys(lista)[n1];
        }
      }
      cod = "";
    }
  }
  return novaPalavra;
}
